ec63/controller_manager:
  ros__parameters:
    update_rate: 50

    ec_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    ec_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

ec63/ec_joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    command_interfaces:
      - position
    state_interfaces:
      - position

    allow_partial_joints_goal: true
